// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportStateKind } from "./ImportStateKind";
import type { ImportSummary } from "./ImportSummary";

export type ImportStatus = { state: ImportStateKind, last_summary: ImportSummary | null, };
