// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFailure } from "./ImportFailure";

export type ImportSummary = { total_scanned: number, created: number, linked: number, skipped: number, failed: number, failures: Array<ImportFailure>, };
