//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "album")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    pub album_type: Option<String>,
    pub release_year: i32,
    pub release_month: Option<i32>,
    pub release_day: Option<i32>,
    pub downloaded: bool,
    pub cover_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::album_artist::Entity")]
    AlbumArtist,
}

impl Related<super::album_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumArtist.def()
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        super::album_artist::Relation::Artist.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::album_artist::Relation::Album.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
