//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

#[allow(unused_imports)]
pub use super::artist::Entity as Artist;
#[allow(unused_imports)]
pub use super::release_group::Entity as ReleaseGroup;
