// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artist } from "./Artist";

export type Album = { id: string, artists: Array<Artist>, title: string, album_type: string | null, release_year: number, release_month: number | null, release_day: number | null, downloaded: boolean, };
