// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Album = { id: string, artist_id: string, title: string, album_type: string | null, jellyfin_id: string | null, musicbrainz_id: string | null, match_method: string | null, };
