// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Alias = { name: string | null, sort_name: string | null, locale: string | null, alias_type: string | null, type_id: string | null, primary: boolean | null, begin: string | null, end: string | null, ended: boolean | null, };
