// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Area = { id: string, name: string, sort_name: string | null, disambiguation: string | null, area_type: string | null, type_id: string | null, };
