// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistSearchResult = { id: string, name: string, country: string | null, disambiguation: string | null, };
