// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtistSummary = { id: string, name: string, profile_image_url: string | null, monitored: boolean, album_count: number, downloaded_album_count: number, };
