// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtworkRefreshCounts } from "./ArtworkRefreshCounts";

export type ArtworkRefreshSummary = { albums: ArtworkRefreshCounts, artists: ArtworkRefreshCounts, };
