// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogScanSummary = { album_directories_found: number, candidates_processed: number, candidates_total: number, albums_imported: number, locations_attached: number, locations_changed: number, unchanged_locations: number, locations_cleared: number, unmatched_candidates: number, ambiguous_matches: number, duplicate_locations: number, skipped_directories: number, failures: number, filesystem_errors: number, };
