// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogScanPhase } from "./CatalogScanPhase";
import type { CatalogScanSummary } from "./CatalogScanSummary";

export type CatalogScan = { phase: CatalogScanPhase, summary: CatalogScanSummary, failure_reason: string | null, };
