// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadJobStatus } from "./DownloadJobStatus";

export type DownloadJob = { id: string, album_id: string, release_name: string, status: DownloadJobStatus, };
