// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artist } from "./Artist";
import type { DownloadJobStatus } from "./DownloadJobStatus";

export type DownloadJob = { id: string, album_id: string, release_name: string | null, artists: Array<Artist>, explicit: boolean | null, available_quality: string | null, status: DownloadJobStatus, enqueued_at: string, started_at: string | null, finished_at: string | null, failure_reason: string | null, };
