// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadJob } from "./DownloadJob";

export type Downloads = { active: Array<DownloadJob>, history: Array<DownloadJob>, };
