// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alias } from "./Alias";
import type { Area } from "./Area";
import type { LifeSpan } from "./LifeSpan";

export type MbArtist = { id: string, name: string, sort_name: string | null, disambiguation: string | null, country: string | null, type: string | null, type_id: string | null, gender: string | null, gender_id: string | null, life_span: LifeSpan | null, area: Area | null, begin_area: Area | null, end_area: Area | null, aliases: Array<Alias> | null, isnis: Array<string> | null, ipis: Array<string> | null, };
