// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MbReleaseGroup = { primary_type: string | null, disambiguation: string | null, id: string, first_release_date: string | null, title: string, };
