// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReleaseGroup = { musicbrainz_id: string, title: string, artist_id: string, type: string, downloaded: boolean, jellyfin_id: string | null, };
