// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MbReleaseGroup } from "./MbReleaseGroup";

export type ReleaseGroupResponse = { release_group_count: number, release_groups: Array<MbReleaseGroup>, };
