// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TidalArtist } from "./TidalArtist";

export type TidalAlbumSearchHit = { id: string, title: string, cover_url: string | null, album_type: string, release_date: string | null, popularity: number, artists: Array<TidalArtist>, };
