// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TidalAlbum = { id: string, title: string, type: string, release_date: string | null, popularity: number, };
