// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TidalAlbumSearchHit } from "./TidalAlbumSearchHit";

export type TidalAlbumSearchResults = { albums: Array<TidalAlbumSearchHit>, returned_count: number, };
